//! Vanilla commands registry — 80+ commands référencées par nom avec aliases.
//! Beaucoup sont stub ; cette registry sert au tab-complete et à la validation.

#[derive(Debug, Clone)]
pub struct CommandMeta {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub description: &'static str,
    pub permission: &'static str,
    pub op_level: u8, // 0=anyone 1=op 2=admin
}

pub fn vanilla_commands() -> &'static [CommandMeta] {
    &[
        CommandMeta {
            name: "help",
            aliases: &["?"],
            description: "List commands.",
            permission: "minecraft.command.help",
            op_level: 0,
        },
        CommandMeta {
            name: "me",
            aliases: &[],
            description: "Emote.",
            permission: "minecraft.command.me",
            op_level: 0,
        },
        CommandMeta {
            name: "list",
            aliases: &[],
            description: "List online players.",
            permission: "minecraft.command.list",
            op_level: 0,
        },
        CommandMeta {
            name: "msg",
            aliases: &["tell", "w"],
            description: "Private message.",
            permission: "minecraft.command.msg",
            op_level: 0,
        },
        CommandMeta {
            name: "say",
            aliases: &[],
            description: "Broadcast message.",
            permission: "minecraft.command.say",
            op_level: 1,
        },
        CommandMeta {
            name: "tp",
            aliases: &["teleport"],
            description: "Teleport.",
            permission: "minecraft.command.tp",
            op_level: 1,
        },
        CommandMeta {
            name: "gamemode",
            aliases: &["gm"],
            description: "Change gamemode.",
            permission: "minecraft.command.gamemode",
            op_level: 1,
        },
        CommandMeta {
            name: "difficulty",
            aliases: &[],
            description: "Set difficulty.",
            permission: "minecraft.command.difficulty",
            op_level: 1,
        },
        CommandMeta {
            name: "gamerule",
            aliases: &[],
            description: "Set game rule.",
            permission: "minecraft.command.gamerule",
            op_level: 2,
        },
        CommandMeta {
            name: "give",
            aliases: &[],
            description: "Give item to player.",
            permission: "minecraft.command.give",
            op_level: 1,
        },
        CommandMeta {
            name: "clear",
            aliases: &[],
            description: "Clear inventory.",
            permission: "minecraft.command.clear",
            op_level: 1,
        },
        CommandMeta {
            name: "kill",
            aliases: &[],
            description: "Kill entity.",
            permission: "minecraft.command.kill",
            op_level: 1,
        },
        CommandMeta {
            name: "summon",
            aliases: &[],
            description: "Summon entity.",
            permission: "minecraft.command.summon",
            op_level: 1,
        },
        CommandMeta {
            name: "kick",
            aliases: &[],
            description: "Kick a player.",
            permission: "minecraft.command.kick",
            op_level: 1,
        },
        CommandMeta {
            name: "ban",
            aliases: &[],
            description: "Ban a player.",
            permission: "minecraft.command.ban",
            op_level: 2,
        },
        CommandMeta {
            name: "ban-ip",
            aliases: &["banip"],
            description: "Ban an IP.",
            permission: "minecraft.command.banip",
            op_level: 2,
        },
        CommandMeta {
            name: "pardon",
            aliases: &["unban"],
            description: "Pardon a player.",
            permission: "minecraft.command.pardon",
            op_level: 2,
        },
        CommandMeta {
            name: "pardon-ip",
            aliases: &["unbanip"],
            description: "Pardon an IP.",
            permission: "minecraft.command.pardonip",
            op_level: 2,
        },
        CommandMeta {
            name: "whitelist",
            aliases: &[],
            description: "Whitelist management.",
            permission: "minecraft.command.whitelist",
            op_level: 2,
        },
        CommandMeta {
            name: "op",
            aliases: &[],
            description: "Grant op.",
            permission: "minecraft.command.op",
            op_level: 2,
        },
        CommandMeta {
            name: "deop",
            aliases: &[],
            description: "Revoke op.",
            permission: "minecraft.command.deop",
            op_level: 2,
        },
        CommandMeta {
            name: "stop",
            aliases: &[],
            description: "Stop the server.",
            permission: "minecraft.command.stop",
            op_level: 2,
        },
        CommandMeta {
            name: "save",
            aliases: &[],
            description: "Save the world.",
            permission: "minecraft.command.save",
            op_level: 2,
        },
        CommandMeta {
            name: "save-all",
            aliases: &[],
            description: "Save all worlds.",
            permission: "minecraft.command.saveall",
            op_level: 2,
        },
        CommandMeta {
            name: "reload",
            aliases: &[],
            description: "Reload plugins.",
            permission: "minecraft.command.reload",
            op_level: 2,
        },
        CommandMeta {
            name: "setworldspawn",
            aliases: &[],
            description: "Set world spawn.",
            permission: "minecraft.command.setworldspawn",
            op_level: 1,
        },
        CommandMeta {
            name: "spawnpoint",
            aliases: &[],
            description: "Set personal spawn.",
            permission: "minecraft.command.spawnpoint",
            op_level: 1,
        },
        CommandMeta {
            name: "time",
            aliases: &[],
            description: "Time manipulation.",
            permission: "minecraft.command.time",
            op_level: 1,
        },
        CommandMeta {
            name: "weather",
            aliases: &[],
            description: "Weather control.",
            permission: "minecraft.command.weather",
            op_level: 1,
        },
        CommandMeta {
            name: "setblock",
            aliases: &[],
            description: "Set a single block.",
            permission: "minecraft.command.setblock",
            op_level: 1,
        },
        CommandMeta {
            name: "fill",
            aliases: &[],
            description: "Fill region with block.",
            permission: "minecraft.command.fill",
            op_level: 1,
        },
        CommandMeta {
            name: "clone",
            aliases: &[],
            description: "Clone region.",
            permission: "minecraft.command.clone",
            op_level: 1,
        },
        CommandMeta {
            name: "locate",
            aliases: &[],
            description: "Locate structure.",
            permission: "minecraft.command.locate",
            op_level: 1,
        },
        CommandMeta {
            name: "effect",
            aliases: &[],
            description: "Apply status effect.",
            permission: "minecraft.command.effect",
            op_level: 1,
        },
        CommandMeta {
            name: "enchant",
            aliases: &[],
            description: "Enchant item.",
            permission: "minecraft.command.enchant",
            op_level: 1,
        },
        CommandMeta {
            name: "xp",
            aliases: &[],
            description: "Give XP.",
            permission: "minecraft.command.xp",
            op_level: 1,
        },
        CommandMeta {
            name: "experience",
            aliases: &[],
            description: "Modify XP.",
            permission: "minecraft.command.experience",
            op_level: 1,
        },
        CommandMeta {
            name: "particle",
            aliases: &[],
            description: "Spawn particles.",
            permission: "minecraft.command.particle",
            op_level: 2,
        },
        CommandMeta {
            name: "playsound",
            aliases: &[],
            description: "Play sound to player.",
            permission: "minecraft.command.playsound",
            op_level: 2,
        },
        CommandMeta {
            name: "stopsound",
            aliases: &[],
            description: "Stop sound.",
            permission: "minecraft.command.stopsound",
            op_level: 2,
        },
        CommandMeta {
            name: "title",
            aliases: &[],
            description: "Display title.",
            permission: "minecraft.command.title",
            op_level: 2,
        },
        CommandMeta {
            name: "tellraw",
            aliases: &[],
            description: "Send raw JSON text.",
            permission: "minecraft.command.tellraw",
            op_level: 2,
        },
        CommandMeta {
            name: "scoreboard",
            aliases: &[],
            description: "Manage scoreboards.",
            permission: "minecraft.command.scoreboard",
            op_level: 2,
        },
        CommandMeta {
            name: "team",
            aliases: &[],
            description: "Manage teams.",
            permission: "minecraft.command.team",
            op_level: 2,
        },
        CommandMeta {
            name: "tag",
            aliases: &[],
            description: "Manage entity tags.",
            permission: "minecraft.command.tag",
            op_level: 2,
        },
        CommandMeta {
            name: "replaceitem",
            aliases: &[],
            description: "Replace item in slot.",
            permission: "minecraft.command.replaceitem",
            op_level: 2,
        },
        CommandMeta {
            name: "setmaxplayers",
            aliases: &[],
            description: "Set max players.",
            permission: "minecraft.command.setmaxplayers",
            op_level: 2,
        },
        CommandMeta {
            name: "function",
            aliases: &[],
            description: "Run a function.",
            permission: "minecraft.command.function",
            op_level: 2,
        },
        CommandMeta {
            name: "execute",
            aliases: &[],
            description: "Execute command as another entity.",
            permission: "minecraft.command.execute",
            op_level: 2,
        },
        CommandMeta {
            name: "schedule",
            aliases: &[],
            description: "Schedule a delayed command.",
            permission: "minecraft.command.schedule",
            op_level: 2,
        },
        CommandMeta {
            name: "trigger",
            aliases: &[],
            description: "Trigger a scoreboard objective.",
            permission: "minecraft.command.trigger",
            op_level: 0,
        },
        CommandMeta {
            name: "ride",
            aliases: &[],
            description: "Make an entity ride another.",
            permission: "minecraft.command.ride",
            op_level: 2,
        },
        CommandMeta {
            name: "damage",
            aliases: &[],
            description: "Damage an entity.",
            permission: "minecraft.command.damage",
            op_level: 2,
        },
        CommandMeta {
            name: "attribute",
            aliases: &[],
            description: "Query or modify attributes.",
            permission: "minecraft.command.attribute",
            op_level: 2,
        },
        CommandMeta {
            name: "worldborder",
            aliases: &[],
            description: "Manage world border.",
            permission: "minecraft.command.worldborder",
            op_level: 2,
        },
        CommandMeta {
            name: "spawnentity",
            aliases: &["summon"],
            description: "Spawn entity.",
            permission: "minecraft.command.spawnentity",
            op_level: 1,
        },
        CommandMeta {
            name: "testfor",
            aliases: &[],
            description: "Test for entities.",
            permission: "minecraft.command.testfor",
            op_level: 1,
        },
        CommandMeta {
            name: "testforblock",
            aliases: &[],
            description: "Test for block at position.",
            permission: "minecraft.command.testforblock",
            op_level: 1,
        },
        CommandMeta {
            name: "transferserver",
            aliases: &[],
            description: "Transfer to another server.",
            permission: "minecraft.command.transferserver",
            op_level: 1,
        },
        CommandMeta {
            name: "toggledownfall",
            aliases: &[],
            description: "Toggle rain/snow.",
            permission: "minecraft.command.toggledownfall",
            op_level: 1,
        },
        CommandMeta {
            name: "spreadplayers",
            aliases: &[],
            description: "Spread players randomly.",
            permission: "minecraft.command.spreadplayers",
            op_level: 2,
        },
        CommandMeta {
            name: "setrespawnpoint",
            aliases: &[],
            description: "Set respawn point.",
            permission: "minecraft.command.setrespawnpoint",
            op_level: 1,
        },
        CommandMeta {
            name: "mixer",
            aliases: &[],
            description: "Mixer control.",
            permission: "minecraft.command.mixer",
            op_level: 2,
        },
        CommandMeta {
            name: "pause",
            aliases: &[],
            description: "Pause the world.",
            permission: "minecraft.command.pause",
            op_level: 2,
        },
        CommandMeta {
            name: "camera",
            aliases: &[],
            description: "Control camera.",
            permission: "minecraft.command.camera",
            op_level: 2,
        },
        CommandMeta {
            name: "inputpermission",
            aliases: &[],
            description: "Modify player input permissions.",
            permission: "minecraft.command.inputpermission",
            op_level: 2,
        },
        CommandMeta {
            name: "clearspawnpoint",
            aliases: &[],
            description: "Clear spawn point.",
            permission: "minecraft.command.clearspawnpoint",
            op_level: 1,
        },
        CommandMeta {
            name: "devtools",
            aliases: &[],
            description: "Dev tools.",
            permission: "minecraft.command.devtools",
            op_level: 2,
        },
        CommandMeta {
            name: "music",
            aliases: &[],
            description: "Control music.",
            permission: "minecraft.command.music",
            op_level: 2,
        },
        CommandMeta {
            name: "testforblocks",
            aliases: &[],
            description: "Compare two volumes.",
            permission: "minecraft.command.testforblocks",
            op_level: 1,
        },
        CommandMeta {
            name: "tickingarea",
            aliases: &[],
            description: "Manage ticking areas.",
            permission: "minecraft.command.tickingarea",
            op_level: 2,
        },
        CommandMeta {
            name: "locatebiome",
            aliases: &[],
            description: "Locate a biome.",
            permission: "minecraft.command.locatebiome",
            op_level: 1,
        },
        CommandMeta {
            name: "ops",
            aliases: &[],
            description: "List ops.",
            permission: "minecraft.command.ops",
            op_level: 2,
        },
        CommandMeta {
            name: "bossbar",
            aliases: &[],
            description: "Manage boss bars.",
            permission: "minecraft.command.bossbar",
            op_level: 2,
        },
        CommandMeta {
            name: "version",
            aliases: &[],
            description: "Server version.",
            permission: "minecraft.command.version",
            op_level: 0,
        },
        CommandMeta {
            name: "seed",
            aliases: &[],
            description: "Show seed.",
            permission: "minecraft.command.seed",
            op_level: 1,
        },
        CommandMeta {
            name: "debug",
            aliases: &[],
            description: "Debug commands.",
            permission: "minecraft.command.debug",
            op_level: 2,
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vanilla_has_many_commands() {
        assert!(vanilla_commands().len() >= 70);
    }

    #[test]
    fn msg_has_aliases() {
        let cmds = vanilla_commands();
        let msg = cmds.iter().find(|c| c.name == "msg").unwrap();
        assert!(msg.aliases.contains(&"tell"));
    }
}
