//! Particles registry — port conceptuel. Liste des particules vanilla Bedrock
//! avec leurs noms identifiant-string pour `SpawnParticleEffectPacket`.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParticleKind {
    BasicFlame,
    BasicSmoke,
    BasicBubble,
    LargeSmoke,
    Explosion,
    ExplosionLarge,
    Lava,
    LavaDrip,
    WaterDrip,
    Rain,
    Spell,
    SpellInstant,
    Mobspell,
    Crit,
    MagicCrit,
    Angry,
    Happy,
    Heart,
    Flame,
    Enchant,
    Snow,
    Portal,
    EnchantingTableParticle,
    Note,
    TotemOfUndying,
    WitchSpell,
    DragonBreath,
    EndRod,
    EntityEffect,
    InstantEffect,
    MobEffectWitch,
    SquidInk,
    Bubble,
    BubblePop,
    BubbleColumnUp,
    BubbleColumnDown,
    CurrentDown,
    Sneeze,
    Splash,
    RisingBubbles,
    ExplosionHugeB,
    Dust,
    Dragon,
    FallingWater,
    FallingLava,
    Ink,
    Fireworks,
    Nautilus,
    Campfire,
    SoulFlame,
    SoulFire,
    Soul,
    SculkSoul,
    SculkCharge,
    SculkChargePop,
    ShriekerSoul,
    CherryLeaves,
}

impl ParticleKind {
    pub fn network_name(&self) -> &'static str {
        match self {
            Self::BasicFlame => "minecraft:basic_flame_particle",
            Self::BasicSmoke => "minecraft:basic_smoke_particle",
            Self::BasicBubble => "minecraft:basic_bubble_particle",
            Self::LargeSmoke => "minecraft:large_smoke_particle",
            Self::Explosion => "minecraft:explosion_particle",
            Self::ExplosionLarge => "minecraft:huge_explosion_emitter",
            Self::Lava => "minecraft:lava_particle",
            Self::LavaDrip => "minecraft:drip_lava_particle",
            Self::WaterDrip => "minecraft:drip_water_particle",
            Self::Rain => "minecraft:rain_splash_particle",
            Self::Spell => "minecraft:mobflame_emitter",
            Self::SpellInstant => "minecraft:mobspell_emitter",
            Self::Mobspell => "minecraft:mobspell_emitter",
            Self::Crit => "minecraft:critical_hit_emitter",
            Self::MagicCrit => "minecraft:enchanted_hit_emitter",
            Self::Angry => "minecraft:villager_angry",
            Self::Happy => "minecraft:villager_happy",
            Self::Heart => "minecraft:heart_particle",
            Self::Flame => "minecraft:basic_flame_particle",
            Self::Enchant => "minecraft:enchanting_table_particle",
            Self::Snow => "minecraft:snowflake_particle",
            Self::Portal => "minecraft:portal_directional",
            Self::EnchantingTableParticle => "minecraft:enchanting_table_particle",
            Self::Note => "minecraft:note_particle",
            Self::TotemOfUndying => "minecraft:totem_particle",
            Self::WitchSpell => "minecraft:witchspell_emitter",
            Self::DragonBreath => "minecraft:dragonbreath_particle",
            Self::EndRod => "minecraft:endrod_particle",
            Self::EntityEffect => "minecraft:mobspell_emitter",
            Self::InstantEffect => "minecraft:mobspell_instant_emitter",
            Self::MobEffectWitch => "minecraft:witchspell_emitter",
            Self::SquidInk => "minecraft:ink_emitter",
            Self::Bubble => "minecraft:basic_bubble_particle",
            Self::BubblePop => "minecraft:bubble_pop_particle",
            Self::BubbleColumnUp => "minecraft:bubble_column_up_particle",
            Self::BubbleColumnDown => "minecraft:bubble_column_down_particle",
            Self::CurrentDown => "minecraft:water_drip_particle",
            Self::Sneeze => "minecraft:sneeze_emitter",
            Self::Splash => "minecraft:water_splash_particle",
            Self::RisingBubbles => "minecraft:rising_bubbles_particle",
            Self::ExplosionHugeB => "minecraft:huge_explosion_emitter",
            Self::Dust => "minecraft:dust_particle",
            Self::Dragon => "minecraft:dragon_particle",
            Self::FallingWater => "minecraft:water_drip_particle",
            Self::FallingLava => "minecraft:falling_lava_particle",
            Self::Ink => "minecraft:ink_emitter",
            Self::Fireworks => "minecraft:sparkler_emitter",
            Self::Nautilus => "minecraft:nautilus_particle",
            Self::Campfire => "minecraft:campfire_smoke_particle",
            Self::SoulFlame => "minecraft:soul_flame_particle",
            Self::SoulFire => "minecraft:soul_flame_particle",
            Self::Soul => "minecraft:soul_particle",
            Self::SculkSoul => "minecraft:sculk_soul_emitter",
            Self::SculkCharge => "minecraft:sculk_charge_particle",
            Self::SculkChargePop => "minecraft:sculk_charge_pop_particle",
            Self::ShriekerSoul => "minecraft:shrieker_particle",
            Self::CherryLeaves => "minecraft:cherry_leaves_particle",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn particle_name_matches_format() {
        assert!(ParticleKind::Explosion
            .network_name()
            .starts_with("minecraft:"));
        assert!(ParticleKind::SoulFlame.network_name().contains("soul"));
    }
}
