use mc_rs_proto::io::ProtoWriter;

/// World state that ticks every server tick.
pub struct WorldState {
    /// World time in ticks (0-24000 cycle, 0=sunrise, 6000=noon, 12000=sunset, 18000=midnight)
    pub time: i32,
    /// Ticks since last SetTime broadcast
    time_broadcast_counter: u32,
    /// Whether the day/night cycle advances
    pub do_daylight_cycle: bool,

    // Weather
    pub is_raining: bool,
    pub is_thundering: bool,
    pub rain_level: f32, // 0.0 - 1.0 (smooth transition)
    pub rain_target: f32,
    pub lightning_level: f32, // 0.0 - 1.0
    pub lightning_target: f32,
    pub weather_duration: i32, // ticks remaining for current weather
    pub do_weather_cycle: bool,
}

impl WorldState {
    pub fn new(do_daylight_cycle: bool, do_weather_cycle: bool) -> Self {
        Self {
            time: 0,
            time_broadcast_counter: 0,
            do_daylight_cycle,
            is_raining: false,
            is_thundering: false,
            rain_level: 0.0,
            rain_target: 0.0,
            lightning_level: 0.0,
            lightning_target: 0.0,
            weather_duration: 12000, // 10 minutes
            do_weather_cycle,
        }
    }

    /// Tick the world. Returns packets to broadcast to all players.
    /// Call this every server tick (10ms = 100 TPS).
    /// World time advances every 5 server ticks to match Minecraft's 20 TPS game tick rate.
    pub fn tick(&mut self) -> Vec<WorldPacket> {
        let mut packets = Vec::new();

        // Day/night cycle — advance 1 game tick every 5 server ticks
        // Server runs at 100 TPS, Minecraft game logic at 20 TPS
        // 24000 game ticks / 20 TPS = 1200 seconds = 20 minutes (correct MC cycle)
        self.time_broadcast_counter += 1;
        if self.do_daylight_cycle && self.time_broadcast_counter.is_multiple_of(5) {
            self.time += 1;
            if self.time >= 24000 {
                self.time = 0;
            }
        }

        // Broadcast time every 200 server ticks (2 seconds)
        if self.time_broadcast_counter >= 200 {
            self.time_broadcast_counter = 0;
            packets.push(WorldPacket::SetTime(self.time));
        }

        // Weather transitions (smooth)
        if self.do_weather_cycle {
            self.weather_duration -= 1;
            if self.weather_duration <= 0 {
                self.cycle_weather();
            }
        }

        // Smooth rain transition
        if self.rain_level < self.rain_target {
            self.rain_level = (self.rain_level + 0.01).min(self.rain_target);
        } else if self.rain_level > self.rain_target {
            self.rain_level = (self.rain_level - 0.01).max(self.rain_target);
        }

        // Smooth lightning transition
        if self.lightning_level < self.lightning_target {
            self.lightning_level = (self.lightning_level + 0.01).min(self.lightning_target);
        } else if self.lightning_level > self.lightning_target {
            self.lightning_level = (self.lightning_level - 0.01).max(self.lightning_target);
        }

        packets
    }

    /// Set time directly (from /time set command).
    pub fn set_time(&mut self, time: i32) {
        self.time = time % 24000;
        self.time_broadcast_counter = 199; // force broadcast next tick
    }

    /// Set weather directly (from /weather command).
    pub fn set_weather(&mut self, rain: bool, thunder: bool) {
        self.is_raining = rain;
        self.is_thundering = thunder;
        self.rain_target = if rain { 1.0 } else { 0.0 };
        self.lightning_target = if thunder { 1.0 } else { 0.0 };
        self.weather_duration = 6000 + (rand::random::<i32>() % 6000).abs(); // 1-2 minutes
    }

    fn cycle_weather(&mut self) {
        // Random next weather state
        let roll: u8 = rand::random::<u8>() % 10;
        if roll < 6 {
            // 60% clear
            self.set_weather(false, false);
        } else if roll < 9 {
            // 30% rain
            self.set_weather(true, false);
        } else {
            // 10% thunder
            self.set_weather(true, true);
        }
    }
}

/// Packets generated by world tick.
pub enum WorldPacket {
    SetTime(i32),
}

/// Encode SetTime packet (0x0A).
pub fn encode_set_time(time: i32) -> Vec<u8> {
    let mut w = ProtoWriter::with_capacity(4);
    w.write_var_i32(time);
    w.into_bytes()
}

/// Encode LevelEvent packet (0x19).
/// Used for weather events (rain start/stop, thunder).
pub fn encode_level_event(event_id: i32, position: [f32; 3], data: i32) -> Vec<u8> {
    let mut w = ProtoWriter::with_capacity(20);
    w.write_var_i32(event_id);
    w.write_f32_le(position[0]);
    w.write_f32_le(position[1]);
    w.write_f32_le(position[2]);
    w.write_var_i32(data);
    w.into_bytes()
}
