[package]
name = "mc-rs-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mc-rs-server"
path = "src/main.rs"

[dependencies]
mc-rs-raknet = { path = "../mc-rs-raknet" }
mc-rs-proto = { path = "../mc-rs-proto" }
tokio = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
snap = { workspace = true }
flate2 = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
